### ISSUE TITLE
mudança no retorno de uma chamada do AM levanta exception na API Thrift

### ISSUE THREAD

**Issue by jfunez** [scieloorg/articles_meta#155]
Com @patymori  rastreamos a sequência de chamadas que provocam o erro:

## ERRO no log do container thrift server:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/rq/worker.py", line 793, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python2.7/site-packages/rq/job.py", line 599, in perform
    self._result = self._execute()
  File "/usr/local/lib/python2.7/site-packages/rq/job.py", line 605, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/app/opac_proc/extractors/jobs.py", line 37, in task_extract_one_collection
    extractor.extract()
  File "/app/opac_proc/extractors/decorators.py", line 17, in wrapped
    extract_method(*args, **kwargs)
  File "/app/opac_proc/extractors/ex_collections.py", line 92, in extract
    for col in self.articlemeta.get_collections():
  File "/app/opac_proc/extractors/source_clients/amapi_wrapper/custom_amapi_client.py", line 77, in get_collections
    for obj in objs:
  File "/usr/local/lib/python2.7/site-packages/articlemeta/client.py", line 1170, in collections
    'get_collection_identifiers'
  File "/usr/local/lib/python2.7/site-packages/articlemeta/client.py", line 675, in dispatcher
    raise ServerError(msg)
ServerError: Error requesting articlemeta: get_collection_identifiers args: () kwargs: {} message: TTransportException(message='TSocket read 0 bytes', type=4)
```

## Dispatcher espera um chave: "code" 

https://github.com/scieloorg/articles_meta/blob/beta/articlemeta/thrift/server.py#L86
-> 
```
class Dispatcher(object):
    ...    
    def get_collection_identifiers(self):
        ...
        data = self._databroker.identifiers_collection()
        ...
        return [articlemeta_thrift.collection(i['code'], i['acron'],
              i['acron2'], i['status'], i['domain'], i['original_name'],
              i['has_analytics'], i['is_active'], i['type']) for i in data]
```

### Somente filtra pelo type == 'journal' mas retorna dados (dict) sem code (type == 'books')

https://github.com/scieloorg/articles_meta/blob/beta/articlemeta/controller.py#L983-L988
->

```
class CollectionMeta:
    ...

    def identifiers(self):
        ...
        collections = self._data
        [self._add_counts(collection, docs_count) for collection in collections if collection.get('type') == 'journals']
        return collections
```
## retorno do AM: todos menos um são do type journal, mas um deles é type books, sem 'code'

```
...
{'domain': 'books.scielo.org',
  'has_analytics': False,
  'is_active': True,
  'name': {'en': 'SciELO Books', 'es': 'SciELO Libros', 'pt': 'SciELO Livros'},
  'type': 'books'},
...
```

## Traceback na chamada do Thrift Server
```
ERROR:thriftpy.server:'code'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/thriftpy/server.py", line 95, in handle
    self.processor.process(iprot, oprot)
  File "/usr/local/lib/python3.5/site-packages/thriftpy/thrift.py", line 304, in process
    self.handle_exception(e, result)
  File "/usr/local/lib/python3.5/site-packages/thriftpy/thrift.py", line 301, in process
    result.success = call()
  File "/usr/local/lib/python3.5/site-packages/thriftpy/thrift.py", line 266, in call
    return f(*(args.__dict__[k] for k in api_args))
  File "/usr/local/lib/python3.5/site-packages/articlemeta/thrift/server.py", line 86, in get_collection_identifiers
    i['has_analytics'], i['is_active'], i['type']) for i in data]
  File "/usr/local/lib/python3.5/site-packages/articlemeta/thrift/server.py", line 86, in <listcomp>
    i['has_analytics'], i['is_active'], i['type']) for i in data]
KeyError: 'code'
```

O bug foi inserido em este commit:
https://github.com/scieloorg/articles_meta/commit/23ec0af5911df807aba60ca4b66002ec0476d353#diff-56549ed9f6e94c1be21257ac64819fcaR986

**Comment by patymori** [comment]
Feita correção e deploy da aplicação em produção. O problema não ocorreu mais.
